# Numerical Computing Using Numpy

<!-- Basic Introduction of Numpy -->
Numpy Stands for Numerical Python, which is a powerful opensource library for Scientific computing. Numpy is created by travis Oliphant in 2005. Numpy is built on C and Frontran.

Core object of Numpy is that it introduces ndarray(N-dimensional array) object, multi dimensional container.

Multi-dimensional container: This means the object (in this case, the ndarray) can hold data arranged in multiple dimensions or axes. For example, it can represent a 1D list, a 2D matrix, a 3D tensor, or higher dimensions depending on the shape you define. Each dimension corresponds to an axis in the array.

Homogeneous data elements: All elements stored in this container must be of the same data type, such as all integers, all floating-point numbers, or all booleans. This uniformity is important for memory efficiency and fast computations.

Usually numbers: The typical use case is numerical data (integers, floats, etc.), as ndarray is designed primarily for scientific computing and numerical operations

Why Numpy?

Numpy is core library for Numerical Computing. It provides fast, efficient and flexible tools for handling large datasets. Numpy is a base NumPy forms the foundational base of the entire PyData ecosystem, which includes widely-used libraries like Pandas, Scikit-learn, and TensorFlow. This is because NumPy provides the core data structure—the ndarray, a fast and efficient multi-dimensional array for homogeneous numerical data—that these libraries build upon to perform their operations. NumPy offers vectorized operations, broadcasting, and a wide range of mathematical and statistical functions that enable efficient data manipulation and numerical computation.

By standardizing the way numerical data is represented and processed, NumPy allows other libraries to seamlessly interoperate and leverage optimized numerical routines implemented in C and Fortran. For example, Pandas uses NumPy arrays as the underlying data storage for its DataFrames, Scikit-learn relies on NumPy arrays for machine learning algorithms, and TensorFlow uses array-like tensors that conceptually build on the same idea of efficient, multi-dimensional numerical data.

Thus, NumPy's ndarray is the computational backbone supporting the performance, scalability, and interoperability of the PyData ecosystem's diverse tools for data analysis, machine learning, and scientific computing

## Objective : To perform Numerical Operations Using Numpy arrays

## Process/ Procedure

### creating Numpy arrays / n-d array

In [3]:
import numpy as np

# np.array()
# inside this function we have to send a list 

arey = np.array([1,2,4,5,6])
print(arey)

[1 2 4 5 6]


In [10]:
type(arey)

numpy.ndarray

In [13]:
two_d_arey = np.array([[1,2,3], [6,7,8]])

In [14]:
two_d_arey

array([[1, 2, 3],
       [6, 7, 8]])

### using np.zeros()
we give like shapes of rows and columns by specifying tuple inside a zeros(). It creates ndarray,
so it give all the elements as O

In [21]:
# here 3,4 initializes 3 rows and 4 columns of 0
arey3 = np.zeros((3,4))
arey3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### using np.ones()
same like zeros , it creates nd array giving all elements as 1

In [22]:
# here 4,6 initializes 4 rows and 6 columns of 1
arey4 = np.ones((4,6))
arey4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
# identity creates identity matrix ie diagonal 1 and other 0
# here 5 initializes 5 * 5 identity matrix
arey5 = np.identity(5)
arey5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# its like range in python but arange generates array of range 7 starting from 0 
# so output will be from 0 to 6
arey6 = np.arange(7)
arey6

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
# here this provides only data types even we used range because 4 is > 3 
arey7 = np.arange(4,3)
arey7

array([], dtype=int64)

In [36]:
# here it gives a range starting from 2 to 8 because we specified start and end 
arey8 = np.arange(2,9)
arey8

array([2, 3, 4, 5, 6, 7, 8])

In [37]:
# arange(start, stop, step): Generates numbers starting from start, incrementing by step, up to (but not including) stop.
arey9 = np.arange(5,32,3)
arey9

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [42]:
# Generates a fixed number of evenly spaced values (lowerrange, upperrange, equidistance jump or steps )
# its like equally dividing a line  or linearly spaced
arey10 = np.linspace(10,20,10)
arey10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [41]:
arey11 = np.linspace(0,9,3)
arey11

array([0. , 4.5, 9. ])

In [45]:
# we can copy any array
arey12 = arey11.copy()
arey12

array([0. , 4.5, 9. ])

In [46]:
arey13 = arey.copy()
arey13

array([1, 2, 4, 5, 6])

In [4]:
 #Array Dimensions in Practice
#0-D Array (Scalar) : A single number 
sc_arrey = np.array(5)
scarrey

array(5)

In [5]:
# 1-D Array (Vector) : A simple list of number. the most common and basic array
vec_arrey = np.array([6,7,8])
vec_arrey

array([6, 7, 8])

In [6]:
#2-D Array (Matrix) : A table with rows and columns. Used to represent matrices 
mat_arrey = np.array([[1,2,4], [7,8,9]])
mat_arrey

array([[1, 2, 4],
       [7, 8, 9]])

In [9]:
# 3-D Array (Tensor) : A cube of number used for higher data like 
tens_arr = np.array([[[2,3], [4,5]],[[7,8],[9,8]]])
tens_arr

array([[[2, 3],
        [4, 5]],

       [[7, 8],
        [9, 8]]])

In [12]:
#Indexing and Slicing
# Accesing and Modifying elements or sub sections of an array
# 1-D Array (Vector) : Similar to python LIst 
#                   0 1 2 3 4 5 6 7 8   this is indexing
ind_slc = np.array([3,4,5,62,6,7,9,9])
print(ind_slc[0]) # output is 3
print(ind_slc[3]) # Output is 62

3
62


In [14]:
# Slicing
print(ind_slc[0:3])  # Output is 3,4 5
# for slicing the logic is (starting index : ending index but this mentioned index wont be sliced the element before this index will be sliced)

[3 4 5]


In [4]:
# 2-D Array (using [rows, column] notation )
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(matrix[0,2])
# (0,2) means (Element at row 0, Element at column at 2 index )

3


In [7]:
print(matrix[2,1])
#output is 8

8


In [8]:
print(matrix[1:,1:])
# slice whole 1st row and 1st column

[[5 6]
 [8 9]]


In [12]:
print(matrix[2:,2:])
# Slice 2 rows and 2 columns

[[9]]


### Array Operation and Univerasl Functions
Numpy Allows Vectorized operation, appying them element wise withoout loop

In [13]:
# BASIC ARITHMETIC
a = np.array([3,4,5,6,7])
b = np.array([6,4,7,8,9])

a+b

array([ 9,  8, 12, 14, 16])

In [14]:
a-b

array([-3,  0, -2, -2, -2])

In [15]:
a*b

array([18, 16, 35, 48, 63])

In [16]:
a/b

array([0.5       , 1.        , 0.71428571, 0.75      , 0.77777778])

In [17]:
a%b

array([3, 0, 5, 6, 7])

Universal Function : fast Element- Wise Operation
function LIke
Square root
Trigonometric sine
Exponential
Natural Logarithm etc

In [18]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [19]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [20]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

In [21]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

### Mathematical and Statistical Operations
 Aggregation FUnction
sum()
mean()
median()
std()
min()
max()

In [22]:
mero_data = np.array([45,45,56,76,56,7,8,55,34,33])
np.sum(mero_data)

np.int64(415)

In [23]:
np.mean(mero_data)

np.float64(41.5)

In [25]:
np.median(mero_data)

np.float64(45.0)

In [26]:
np.std(mero_data)

np.float64(20.636133358747227)

In [27]:
np.min(mero_data)

np.int64(7)

In [28]:
np.max(mero_data)

np.int64(76)

### Linear Algebra
Matrix Multiplication
Transpose of matrix etc

In [29]:
mat1 = np.array([[2,3], [5,6]])
mat2 = np.array([[3,4],[8,9]])


# MATRIX MULTIPLICATION
print(np.dot(mat1, mat2))

[[30 35]
 [63 74]]


In [30]:
# Transpose of Matrxi
print(mat1.T)

[[2 5]
 [3 6]]


### ARRAY MANIPULATION

Preparing Data often requires changing The structure of arrays

#### Reshaping
changing the shape of an array without changing its data

In [42]:
arere = np.arange(1,17)
arere

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [47]:
reshap = arere.reshape(4,4)
reshap

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# Combining Arrays
arey = np.array([1,2,4,5,6])
brey = np.array([3,7,8,9])
np.concatenate((arey,brey))

array([1, 2, 4, 5, 6, 3, 7, 8, 9])

In [54]:
# Splitting Array
sparey = np.array([1,2,34,4,5,5,5,6,7])
np.split(sparey,3)

[array([ 1,  2, 34]), array([4, 5, 5]), array([5, 6, 7])]

#### BROADCASTING

this is the mechanism that Allows Numpy to work with arrays of different shapes during arithmetic Operations
rule :  Dimension are Compatible when: 
they are equal or 
one of them is 1 
Broadcasting eliminates the need to create duplicate data, making code fast and memory efficient

In [60]:
areys = np.array([[2,3,4]
                 ,[5,6,7]])  # shape is (2,3)

breys = np.array([9,8,7])    # shape is (1,3)

result = areys + breys

result

array([[11, 11, 11],
       [14, 14, 14]])

In [61]:
mul_re = areys * breys
mul_re

array([[18, 24, 28],
       [45, 48, 49]])

In [62]:
sub = areys - breys
sub

array([[-7, -5, -3],
       [-4, -2,  0]])

###### we can see from above that the broadcasting helps to adjust shapes of array